# Generated by Django 4.2.11 on 2024-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0002_remove_packagestatus_dayly_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создание'),
        ),
    ]
