# Generated by Django 4.2.11 on 2024-09-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_tender_for_personal_use_tender_group_purchases_and_more'),
        ('user_cabinet', '0005_status_quantity_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='quantity_opening',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество открытий'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='quantity_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество объявлений'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='quantity_tenders',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество закупок'),
        ),
        migrations.CreateModel(
            name='OpenNumberTenderCount',
            fields=[
                ('opennumbercount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_cabinet.opennumbercount')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers_count', to='tender.tender')),
            ],
            bases=('user_cabinet.opennumbercount',),
        ),
    ]
