# Generated by Django 4.2.11 on 2024-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_tender_for_personal_use_tender_group_purchases_and_more'),
        ('user_cabinet', '0006_cabinet_quantity_opening_cabinet_quantity_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='opened_tender_contacts',
            field=models.ManyToManyField(blank=True, related_name='opened_tender_contacts', to='tender.tender'),
        ),
    ]
