# Generated by Django 4.2.11 on 2024-09-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0007_cabinet_opened_tender_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='base_tariff_connected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='base_tariff',
            field=models.BooleanField(blank=True, default=False, verbose_name='Базовый тариф'),
        ),
    ]
