# Generated by Django 4.2.11 on 2024-10-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0011_alter_status_options_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
