# Generated by Django 4.2.11 on 2024-06-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название колонки')),
                ('formula', models.CharField(max_length=255, verbose_name='Формула расчета')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='Сумма от')),
            ],
            options={
                'verbose_name': 'Колонка цены',
                'verbose_name_plural': 'Колонки цен',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('mini_desc', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Валюта')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Минимальное количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Времея обновления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/%Y/%m/', verbose_name='Картинка')),
                ('phone', models.CharField(blank=True, max_length=123, null=True, verbose_name='Телефон')),
                ('terms_of_sale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Условия продажи')),
                ('country_of_manufacture', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производства')),
                ('characterization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Характеристики')),
                ('product_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/%Y/%m/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.productcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория продуктов',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
    ]
