# Generated by Django 4.2.11 on 2024-07-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategory_is_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_main_category',
        ),
    ]
