# Generated by Django 4.2.11 on 2024-07-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productcategory_is_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('wide_banner', models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Широкий баннер')),
                ('left_banner', models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Левый баннер')),
                ('right_banner', models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Правый баннер')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
