# Generated by Django 4.2.11 on 2024-08-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_wholesale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Большая партия'),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_wholesale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Средняя партия'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_wholesale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Малая партия'),
        ),
    ]
