# Generated by Django 4.2.11 on 2024-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_large_wholesale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='bottom_banner',
            field=models.FileField(blank=True, null=True, upload_to='images/banners/', verbose_name='Нижний баннер'),
        ),
    ]
