# Generated by Django 4.2.11 on 2024-08-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productbanner_bottom_banner_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='provider',
        ),
    ]
