# Generated by Django 4.2.11 on 2024-08-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productcategory_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewCategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_category_name', models.CharField(max_length=255, verbose_name='Новая категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Запрос на добавление новой категории',
                'verbose_name_plural': 'Запросы на добавление новых категорий',
            },
        ),
    ]
