# Generated by Django 4.2.11 on 2024-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_addnewcategoryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/categories/', verbose_name='Иконка'),
        ),
    ]
