# Generated by Django 4.2.11 on 2024-09-26 05:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productbanner_bottom_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order'], 'verbose_name': 'Категория продуктов', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='is_recommended',
        ),

        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.productcategory', verbose_name='Родительская категория'),
        ),
    ]
