# Generated by Django 4.2.11 on 2024-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbanner',
            name='bottom_banner_mobile',
            field=models.FileField(blank=True, upload_to='images/banners/', verbose_name='Нижний баннер моб'),
        ),
        migrations.AddField(
            model_name='productbanner',
            name='wide_banner_mobile',
            field=models.FileField(blank=True, upload_to='images/banners/', verbose_name='Верхний баннер моб'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='wide_banner',
            field=models.FileField(blank=True, upload_to='images/banners/', verbose_name='Верхний баннер'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
