# Generated by Django 4.2.11 on 2024-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('icon', models.FileField(upload_to='images/category/icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PriceFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/price/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Файл цены',
                'verbose_name_plural': 'Файлы цен',
            },
        ),
        migrations.CreateModel(
            name='ProvideFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/providers/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Файл Поставщика',
                'verbose_name_plural': 'Файлы Поставщика',
            },
        ),
        migrations.CreateModel(
            name='ProvideImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/providers/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Изображение Поставщика',
                'verbose_name_plural': 'Изображения Поставщика',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('title', models.CharField(blank=True, max_length=123, null=True, verbose_name='Название')),
                ('mini_descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Короткое описание')),
                ('type', models.CharField(blank=True, choices=[(1, 'Оптовая продажа товаров (вы поставщик)'), (2, 'Производство товаров (вы производитель)'), (3, 'Оказание услуг логистики / поиска товаров / таможенного оформления')], max_length=255, null=True, verbose_name='Тип')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальный заказ')),
                ('company_core_business', models.CharField(choices=[('wholesale', 'Оптовая продажа товаров (вы поставщик)'), ('manufacturing', 'Производство товаров (вы производитель)'), ('services', 'Оказание услуг логистики / поиска товаров / таможенного оформления')], default='wholesale', max_length=20, verbose_name='Основная деятельность вашей компании')),
                ('large_wholesale', models.BooleanField(default=False, verbose_name='Крупный опт')),
                ('small_wholesale', models.BooleanField(default=False, verbose_name='Мелкий опт')),
                ('retail', models.BooleanField(default=False, verbose_name='Поштучно')),
                ('official_distributor', models.BooleanField(blank=True, null=True, verbose_name='Официальный дистрибьютор')),
                ('how_get', models.CharField(blank=True, max_length=200, null=True, verbose_name='Как добраться')),
                ('post_index', models.CharField(blank=True, max_length=123, null=True, verbose_name='Почтовый индекс')),
                ('metro', models.CharField(blank=True, max_length=123, null=True, verbose_name='Метро')),
                ('address', models.CharField(blank=True, max_length=123, null=True, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=123, null=True, verbose_name='Время работы')),
                ('phones', models.CharField(blank=True, max_length=123, null=True, verbose_name='Телефон')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Вебсайт')),
                ('youtube_video', models.URLField(blank=True, null=True, verbose_name='Видео с Ютуба')),
                ('fax', models.CharField(blank=True, max_length=123, null=True, verbose_name='Факс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/providers/avatars/%Y/%m', verbose_name='Аватар')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/providers/banners/%Y/%m', verbose_name='Банер')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Реквизиты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('emp_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во работников')),
                ('register_ur', models.DateField(blank=True, null=True, verbose_name='Дата регистрации юр лица')),
                ('installment', models.BooleanField(blank=True, default=False, verbose_name='Возможна рассрочка')),
                ('credit', models.BooleanField(default=False, verbose_name='Возможен кредит')),
                ('deposit', models.BooleanField(default=False, verbose_name='Возможен депозит')),
                ('consignment', models.BooleanField(default=False, verbose_name='Возможна передача под реализацию')),
                ('dropshipping', models.BooleanField(default=False, verbose_name='Возможен дропшиппинг')),
                ('showroom', models.BooleanField(default=False, verbose_name='Есть шоурум')),
                ('marketplace_sale', models.BooleanField(default=False, verbose_name='Разрешена продажа на маркетплейсах')),
                ('pickup', models.BooleanField(default=False, verbose_name='Самовывоз')),
                ('transport_company', models.BooleanField(default=False, verbose_name='Транспортной компанией')),
                ('by_car', models.BooleanField(default=False, verbose_name='Автомобилем')),
                ('air_transport', models.BooleanField(default=False, verbose_name='Авиатранспортом')),
                ('rail_transport', models.BooleanField(default=False, verbose_name='Железной дорогой')),
                ('courier', models.BooleanField(default=False, verbose_name='Курьером')),
                ('cash', models.BooleanField(default=False, verbose_name='Наличными')),
                ('bank_transfer', models.BooleanField(default=False, verbose_name='Безналичная оплата')),
                ('credit_card', models.BooleanField(default=False, verbose_name='Кредитные карты')),
                ('electronic_money', models.BooleanField(default=False, verbose_name='Электронные деньги')),
                ('is_modered', models.BooleanField(blank=True, default=False, null=True, verbose_name='Прошла модерацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('is_provider', models.BooleanField(default=False, verbose_name='Поставщик')),
                ('comment', models.TextField(blank=True, default='Анкета компании заполнена некорректно! Корректно заполните название компании, описание, контактные данные. Затем подайте на перепроверку.', verbose_name='Комментарий')),
                ('decimal_places', models.PositiveSmallIntegerField(default=0, verbose_name='Десятичные разряды')),
                ('category', models.ManyToManyField(blank=True, related_name='providers', to='provider.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
