# Generated by Django 4.2.11 on 2024-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_provider_type_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='company_core_business',
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(choices=[('wholesale', 'Оптовая продажа товаров (вы поставщик)'), ('manufacturing', 'Производство товаров (вы производитель)'), ('services', 'Оказание услуг логистики / поиска товаров / таможенного оформления')], default='wholesale', max_length=20, verbose_name='Основная деятельность вашей компании'),
        ),
    ]
