# Generated by Django 4.2.11 on 2024-06-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_remove_provider_company_core_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='emp_quantity',
            field=models.CharField(blank=True, null=True, verbose_name='Кол-во работников'),
        ),
    ]
