# Generated by Django 4.2.11 on 2024-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_provider_emp_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.CharField(blank=True, choices=[('wholesale', 'Оптовая продажа товаров (вы поставщик)'), ('manufacturing', 'Производство товаров (вы производитель)'), ('services', 'Оказание услуг логистики / поиска товаров / таможенного оформления')], default='wholesale', max_length=20, null=True, verbose_name='Основная деятельность вашей компании'),
        ),
    ]
