# Generated by Django 4.2.11 on 2024-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_alter_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='emp_quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кол-во работников'),
        ),
    ]
