# Generated by Django 4.2.11 on 2024-06-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_alter_provider_emp_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Ключевые слова'),
        ),
    ]
