# Generated by Django 4.2.11 on 2024-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_provider_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='for_personal_use',
            field=models.BooleanField(default=False, verbose_name='Для собственного потребления'),
        ),
        migrations.AddField(
            model_name='provider',
            name='group_purchases',
            field=models.BooleanField(default=False, verbose_name='Совместные покупки'),
        ),
        migrations.AddField(
            model_name='provider',
            name='marketplaces',
            field=models.BooleanField(default=False, verbose_name='Маркетплейсы'),
        ),
        migrations.AddField(
            model_name='provider',
            name='online_store',
            field=models.BooleanField(default=False, verbose_name='Интернет-магазин'),
        ),
        migrations.AddField(
            model_name='provider',
            name='purchase_frequency',
            field=models.CharField(blank=True, choices=[('once', 'Однократно'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('multiple_times_year', 'Несколько раз в год'), ('twice_year', 'Пару раз в год')], default='once', max_length=20, null=True, verbose_name='Как часто планируете закупать'),
        ),
        migrations.AddField(
            model_name='provider',
            name='retail_store',
            field=models.BooleanField(default=False, verbose_name='Розничный магазин'),
        ),
        migrations.AddField(
            model_name='provider',
            name='social_networks',
            field=models.BooleanField(default=False, verbose_name='Соцсети, доски объявлений'),
        ),
        migrations.AddField(
            model_name='provider',
            name='wholesale_resale',
            field=models.BooleanField(default=False, verbose_name='Оптовая перепродажа'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_modered',
            field=models.BooleanField(default=False, verbose_name='Прошла модерацию'),
        ),
    ]
