# Generated by Django 4.2.11 on 2024-07-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_provider_for_personal_use_provider_group_purchases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='for_personal_use',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='group_purchases',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='marketplaces',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='online_store',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='purchase_frequency',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='retail_store',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='social_networks',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='wholesale_resale',
        ),
    ]
