# Generated by Django 4.2.11 on 2024-07-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_remove_provider_for_personal_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main_category',
            field=models.BooleanField(default=False, verbose_name='Главная категория'),
        ),
    ]
