# Generated by Django 4.2.11 on 2024-08-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_category_is_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='provider_documents/%Y/%m/', verbose_name='Документ')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='provider.provider')),
            ],
        ),
    ]
