# Generated by Django 4.2.11 on 2024-08-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_verificationdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationdocuments',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProviderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='provider.provider')),
            ],
        ),
    ]
