# Generated by Django 4.2.11 on 2024-08-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_verificationdocuments_name_providerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerlink',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='verificationdocuments',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='pricefiles',
            name='file',
            field=models.FileField(upload_to='files/price/%Y/%m/', verbose_name='Файл цены'),
        ),
        migrations.AlterField(
            model_name='providefiles',
            name='image',
            field=models.FileField(upload_to='images/providers/%Y/%m/', verbose_name='Файл Поставщика'),
        ),
        migrations.AlterField(
            model_name='provideimg',
            name='image',
            field=models.ImageField(upload_to='images/providers/%Y/%m/', verbose_name='Изображение Поставщика'),
        ),
    ]
