# Generated by Django 4.2.11 on 2024-08-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_alter_providerlink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdocuments',
            name='name',
        ),
    ]
