# Generated by Django 4.2.11 on 2024-09-26 05:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [

    ]
