# Generated by Django 4.2.11 on 2024-10-02 05:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0018_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [

    ]
