# Generated by Django 4.2.11 on 2024-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='video_verification',
            field=models.FileField(blank=True, null=True, upload_to='files/verification/%Y/%m/', verbose_name='Видео верификация'),
        ),
        migrations.AddField(
            model_name='provider',
            name='video_verification_approve',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
