# Generated by Django 4.2.11 on 2024-10-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0020_provider_video_verification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='video_verification',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='video_verification_approve',
        ),
        migrations.CreateModel(
            name='ProviderVerificationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='provider_videos/%Y/%m/', verbose_name='Видео')),
                ('verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='provider.provider')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
