# Generated by Django 4.2.11 on 2024-06-13 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='settings',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='buyer.bannersettings', verbose_name='Настройки'),
        ),
    ]
