# Generated by Django 4.2.11 on 2024-06-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.bannersettings', verbose_name='Настройки'),
        ),
    ]
