# Generated by Django 4.2.11 on 2024-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_banner_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_vertical',
            field=models.FileField(blank=True, null=True, upload_to='images/banners/vertical/%Y/%m/', verbose_name='Картинка верт'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners/desktop/%Y/%m/', verbose_name='Картинка круп'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners/mobile/%Y/%m/', verbose_name='Картинка моб'),
        ),
    ]
