# Generated by Django 4.2.11 on 2024-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=200, unique=True, verbose_name='Телеграм Бот Токен')),
                ('report_channels', models.TextField(blank=True, max_length=200, null=True, verbose_name='Айди каналов')),
            ],
            options={
                'verbose_name': 'Токен бота Telegram',
                'verbose_name_plural': 'Токены бота Telegram',
            },
        ),
    ]
