# Generated by Django 4.2.11 on 2024-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_staticpage_name_alter_staticpage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambottoken',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
    ]
