# Generated by Django 4.2.11 on 2024-10-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_footercolumn_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='column',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.footercolumn', verbose_name='Колонка'),
            preserve_default=False,
        ),
    ]
