# Generated by Django 4.2.11 on 2024-10-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_footerlink_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.footercolumn', verbose_name='Колонка'),
        ),
    ]
