# Generated by Django 4.2.11 on 2024-10-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_footerlink_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambottoken',
            name='recaptcha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ReCaptcha'),
        ),
    ]
