# Generated by Django 4.2.11 on 2024-10-10 06:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_profilehelptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehelptext',
            name='button1_icon',
            field=models.FileField(blank=True, null=True, upload_to='help_text/', verbose_name='Иконка 1'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='button1_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 1'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='button1_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кнопка 1'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='button2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кнопка 2'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='button2_icon',
            field=models.FileField(blank=True, null=True, upload_to='help_text/', verbose_name='Иконка 2'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='button2_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 2'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='profilehelptext',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
