# Generated by Django 4.2.11 on 2024-10-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_profilehelptext_button1_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilehelptext',
            old_name='button2',
            new_name='button2_text',
        ),
    ]
