# Generated by Django 4.2.11 on 2024-10-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_button2_profilehelptext_button2_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehelptext',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='profilehelptext',
            name='for_users_on_standard_tariff',
            field=models.BooleanField(default=False, verbose_name='Для юзеров на стандартном тариф'),
        ),
        migrations.AddField(
            model_name='profilehelptext',
            name='for_users_without_tariff',
            field=models.BooleanField(default=False, verbose_name='Для юзеров без тарифа'),
        ),
    ]
