# Generated by Django 4.2.11 on 2024-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_profilehelptext_for_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambottoken',
            name='video_verification_icon',
            field=models.FileField(blank=True, null=True, upload_to='telegram_bot/', verbose_name='Иконка проверки видео'),
        ),
    ]
