# Generated by Django 4.2.11 on 2024-06-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('title', models.CharField(max_length=123)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=123, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requirements', models.CharField(blank=True, max_length=123, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('place_of_sale', models.CharField(blank=True, max_length=123, null=True)),
                ('is_phone', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('cash', models.BooleanField(default=False, verbose_name='Наличными')),
                ('bank_transfer', models.BooleanField(default=False, verbose_name='Безналичная оплата')),
                ('credit_card', models.BooleanField(default=False, verbose_name='Кредитные карты')),
                ('electronic_money', models.BooleanField(default=False, verbose_name='Электронные деньги')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provider.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/tenders/')),
                ('tender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tender_images', to='tender.tender')),
            ],
            options={
                'verbose_name': 'Изображении закупки',
                'verbose_name_plural': 'Изображение закупки',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tender.country')),
            ],
            options={
                'verbose_name': 'Регион (Область)',
                'verbose_name_plural': 'Регионы (Области)',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tender.region'),
        ),
    ]
