# Generated by Django 4.2.11 on 2024-06-14 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider', '0006_alter_provider_type'),
        ('tender', '0002_tender_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tender',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='provider.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='is_phone',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие телефона'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='phone',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='place_of_sale',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Место продажи'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='requirements',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
