# Generated by Django 4.2.11 on 2024-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_searchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='for_personal_use',
            field=models.BooleanField(default=False, verbose_name='Для собственного потребления'),
        ),
        migrations.AddField(
            model_name='tender',
            name='group_purchases',
            field=models.BooleanField(default=False, verbose_name='Совместные покупки'),
        ),
        migrations.AddField(
            model_name='tender',
            name='large_wholesale',
            field=models.BooleanField(default=False, verbose_name='Крупный опт'),
        ),
        migrations.AddField(
            model_name='tender',
            name='marketplaces',
            field=models.BooleanField(default=False, verbose_name='Маркетплейсы'),
        ),
        migrations.AddField(
            model_name='tender',
            name='official_distributor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Официальный дистрибьютор'),
        ),
        migrations.AddField(
            model_name='tender',
            name='online_store',
            field=models.BooleanField(default=False, verbose_name='Интернет-магазин'),
        ),
        migrations.AddField(
            model_name='tender',
            name='purchase_frequency',
            field=models.CharField(blank=True, choices=[('once', 'Однократно'), ('weekly', 'Каждую неделю'), ('monthly', 'Каждый месяц'), ('multiple_times_year', 'Несколько раз в год'), ('twice_year', 'Пару раз в год')], default='once', max_length=20, null=True, verbose_name='Как часто планируете закупать'),
        ),
        migrations.AddField(
            model_name='tender',
            name='retail',
            field=models.BooleanField(default=False, verbose_name='Поштучно'),
        ),
        migrations.AddField(
            model_name='tender',
            name='retail_store',
            field=models.BooleanField(default=False, verbose_name='Розничный магазин'),
        ),
        migrations.AddField(
            model_name='tender',
            name='small_wholesale',
            field=models.BooleanField(default=False, verbose_name='Мелкий опт'),
        ),
        migrations.AddField(
            model_name='tender',
            name='social_networks',
            field=models.BooleanField(default=False, verbose_name='Соцсети, доски объявлений'),
        ),
        migrations.AddField(
            model_name='tender',
            name='wholesale_resale',
            field=models.BooleanField(default=False, verbose_name='Оптовая перепродажа'),
        ),
    ]
