# Generated by Django 4.2.11 on 2024-10-08 08:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_tender_for_personal_use_tender_group_purchases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderOpenHelpText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст для помощи',
                'verbose_name_plural': 'Тексты для помощи',
            },
        ),
    ]
