# Generated by Django 4.2.11 on 2024-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_tenderopenhelptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderopenhelptext',
            name='button_link',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка кнопки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderopenhelptext',
            name='button_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
    ]
