# Generated by Django 4.2.11 on 2024-10-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_tenderopenhelptext_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderopenhelptext',
            name='button_link',
        ),
    ]
