# Generated by Django 4.2.11 on 2024-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_before',
            field=models.BooleanField(default=False, verbose_name='Последняя авторизация'),
        ),
    ]
